-- ============================================================================
-- Iceberg V3 Clinical Trial Lab Results — Queries
-- ============================================================================
-- Demonstrates native Iceberg format-version 3 table reading: schema
-- inference from V3 metadata (generated by Spark 4.0 + Iceberg 1.10.1),
-- manifest-based file discovery, site-level aggregations, abnormal result
-- detection, and analyst workload analysis. All queries are read-only.
-- ============================================================================


-- ============================================================================
-- Query 1: Baseline — Total Row Count
-- ============================================================================
-- Verifies that DeltaForge can parse the V3 metadata chain and discover
-- all data files. This is the first test of V3 format compatibility.

ASSERT ROW_COUNT = 480
SELECT * FROM {{zone_name}}.iceberg_demos.lab_results;


-- ============================================================================
-- Query 2: Schema Inference from Iceberg V3 Metadata
-- ============================================================================
-- The schema comes from the V3 metadata.json. This query exercises all 12
-- columns including boolean (is_abnormal) to prove correct type mapping.

ASSERT ROW_COUNT = 480
ASSERT VALUE sample_id IS NOT NULL WHERE sample_id = 'S-00001'
SELECT
    sample_id,
    trial_name,
    site,
    patient_id,
    test_name,
    result_value,
    unit,
    reference_low,
    reference_high,
    is_abnormal,
    collection_date,
    analyst
FROM {{zone_name}}.iceberg_demos.lab_results
ORDER BY sample_id;


-- ============================================================================
-- Query 3: Per-Site Sample Counts
-- ============================================================================
-- Three trial sites with 160 samples each.

ASSERT ROW_COUNT = 3
ASSERT VALUE sample_count = 160 WHERE site = 'Boston-MGH'
ASSERT VALUE sample_count = 160 WHERE site = 'Houston-MD'
ASSERT VALUE sample_count = 160 WHERE site = 'Seattle-UW'
SELECT
    site,
    COUNT(*) AS sample_count
FROM {{zone_name}}.iceberg_demos.lab_results
GROUP BY site
ORDER BY site;


-- ============================================================================
-- Query 4: Per-Test Sample Counts
-- ============================================================================
-- Four lab tests, 120 samples each (40 per site × 3 sites).

ASSERT ROW_COUNT = 4
ASSERT VALUE sample_count = 120 WHERE test_name = 'ALT'
ASSERT VALUE sample_count = 120 WHERE test_name = 'Creatinine'
ASSERT VALUE sample_count = 120 WHERE test_name = 'Hemoglobin'
ASSERT VALUE sample_count = 120 WHERE test_name = 'Platelet-Count'
SELECT
    test_name,
    COUNT(*) AS sample_count
FROM {{zone_name}}.iceberg_demos.lab_results
GROUP BY test_name
ORDER BY test_name;


-- ============================================================================
-- Query 5: Average Result Value by Test
-- ============================================================================
-- Floating-point aggregation across all sites per test type.

ASSERT ROW_COUNT = 4
ASSERT VALUE avg_result = 29.23 WHERE test_name = 'ALT'
ASSERT VALUE avg_result = 0.89 WHERE test_name = 'Creatinine'
ASSERT VALUE avg_result = 14.71 WHERE test_name = 'Hemoglobin'
ASSERT VALUE avg_result = 243.14 WHERE test_name = 'Platelet-Count'
SELECT
    test_name,
    ROUND(AVG(result_value), 2) AS avg_result
FROM {{zone_name}}.iceberg_demos.lab_results
GROUP BY test_name
ORDER BY test_name;


-- ============================================================================
-- Query 6: Abnormal Results per Test
-- ============================================================================
-- Boolean column aggregation — counts samples where result_value falls
-- outside the reference range. Exercises Iceberg V3 boolean type reading.

ASSERT ROW_COUNT = 4
ASSERT VALUE abnormal_count = 15 WHERE test_name = 'ALT'
ASSERT VALUE abnormal_count = 38 WHERE test_name = 'Creatinine'
ASSERT VALUE abnormal_count = 12 WHERE test_name = 'Hemoglobin'
ASSERT VALUE abnormal_count = 19 WHERE test_name = 'Platelet-Count'
SELECT
    test_name,
    SUM(CASE WHEN is_abnormal THEN 1 ELSE 0 END) AS abnormal_count
FROM {{zone_name}}.iceberg_demos.lab_results
GROUP BY test_name
ORDER BY test_name;


-- ============================================================================
-- Query 7: Abnormal Results per Site
-- ============================================================================
-- Site-level quality metric for trial monitoring.

ASSERT ROW_COUNT = 3
ASSERT VALUE abnormal_count = 28 WHERE site = 'Boston-MGH'
ASSERT VALUE abnormal_count = 29 WHERE site = 'Houston-MD'
ASSERT VALUE abnormal_count = 27 WHERE site = 'Seattle-UW'
SELECT
    site,
    SUM(CASE WHEN is_abnormal THEN 1 ELSE 0 END) AS abnormal_count
FROM {{zone_name}}.iceberg_demos.lab_results
GROUP BY site
ORDER BY site;


-- ============================================================================
-- Query 8: Results Above Reference Range
-- ============================================================================
-- Predicate pushdown on double column — identifies samples exceeding the
-- upper reference limit.

ASSERT ROW_COUNT = 31
SELECT
    sample_id,
    site,
    test_name,
    result_value,
    reference_high
FROM {{zone_name}}.iceberg_demos.lab_results
WHERE result_value > reference_high
ORDER BY result_value DESC;


-- ============================================================================
-- Query 9: Results Below Reference Range
-- ============================================================================
-- Identifies samples below the lower reference limit.

ASSERT ROW_COUNT = 53
SELECT
    sample_id,
    site,
    test_name,
    result_value,
    reference_low
FROM {{zone_name}}.iceberg_demos.lab_results
WHERE result_value < reference_low
ORDER BY result_value ASC;


-- ============================================================================
-- Query 10: Analyst Workload Distribution
-- ============================================================================
-- Sample counts per analyst across all sites and tests.

ASSERT ROW_COUNT = 5
ASSERT VALUE sample_count = 90 WHERE analyst = 'Dr. Chen'
ASSERT VALUE sample_count = 100 WHERE analyst = 'Dr. Kovacs'
ASSERT VALUE sample_count = 99 WHERE analyst = 'Dr. Okafor'
ASSERT VALUE sample_count = 100 WHERE analyst = 'Dr. Patel'
ASSERT VALUE sample_count = 91 WHERE analyst = 'Dr. Reyes'
SELECT
    analyst,
    COUNT(*) AS sample_count
FROM {{zone_name}}.iceberg_demos.lab_results
GROUP BY analyst
ORDER BY analyst;


-- ============================================================================
-- Query 11: Distinct Entity Counts
-- ============================================================================
-- Exercises COUNT(DISTINCT ...) across the full dataset.

ASSERT ROW_COUNT = 1
ASSERT VALUE distinct_samples = 480
ASSERT VALUE distinct_patients = 173
ASSERT VALUE distinct_analysts = 5
SELECT
    COUNT(DISTINCT sample_id) AS distinct_samples,
    COUNT(DISTINCT patient_id) AS distinct_patients,
    COUNT(DISTINCT analyst) AS distinct_analysts
FROM {{zone_name}}.iceberg_demos.lab_results;


-- ============================================================================
-- VERIFY: All Checks
-- ============================================================================
-- Cross-cutting sanity check: total rows, grand totals, and key invariants.
-- A user who runs only this query can verify the Iceberg V3 reader works.

ASSERT ROW_COUNT = 1
ASSERT VALUE total_rows = 480
ASSERT VALUE site_count = 3
ASSERT VALUE test_count = 4
ASSERT VALUE total_abnormal = 84
ASSERT VALUE above_range = 31
ASSERT VALUE below_range = 53
ASSERT VALUE distinct_patients = 173
SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT site) AS site_count,
    COUNT(DISTINCT test_name) AS test_count,
    SUM(CASE WHEN is_abnormal THEN 1 ELSE 0 END) AS total_abnormal,
    SUM(CASE WHEN result_value > reference_high THEN 1 ELSE 0 END) AS above_range,
    SUM(CASE WHEN result_value < reference_low THEN 1 ELSE 0 END) AS below_range,
    COUNT(DISTINCT patient_id) AS distinct_patients
FROM {{zone_name}}.iceberg_demos.lab_results;
